// Generated by CoffeeScript 1.4.0

$(document).ready(function() {
  var emitOrientation, socket;
  $('#mobileInput .btn').click(function() {
    return socket.emit('mobileConnectWithCode', $('#mobileInput input').val());
  });
  socket = io.connect('http://127.0.0.1/1337');
  socket.on("connect", function() {});
  socket.on("error", function(error) {
    return alert(error);
  });
  socket.on("serverAcceptedConnection", function(data) {
    return window.addEventListener('deviceorientation', emitOrientation, false);
  });
  emitOrientation = function(e) {
    return socket.emit("ondeviceorientation", {
      alpha: e.alpha,
      beta: e.beta
    });
  };
  return socket.on("lostConnection", function(data) {
    alert('sorry the connection was lost :-(');
    return window.removeEventListener('deviceorientation', emitOrientation, false);
  });
});
