// Generated by CoffeeScript 1.3.3
(function() {
  var socket;

  socket = io.connect();

  socket.on("connect", function() {
    return window.ondeviceorientation = function(e) {
      return socket.emit("ondeviceorientation", {
        alpha: e.alpha,
        beta: e.beta
      });
    };
  });

}).call(this);
